### PR TITLE
Allow building with `mtl-2.3.1`

### LINKED ISSUE #7: Does version constraint on mtl really need to be `<2.3`
I'm able to compile language-c99-simple with mtl 2.3 if I adjust the version bounds in the cabal file to read:

```
mtl >= 2.2.0 && < 2.4
```

Does the version bound on mtl need to be so strict?

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #7.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
A gentle ping on this, @fdedden. Would you be able to merge and release this to Hackage?

**Review by fdedden — APPROVED** [review]
Hi @RyanGlScott, thank you for the ping, I overlooked this PR.

I will do a release as version 0.2.3 immediately.

**Comment by fdedden** [comment]
I have released the package: https://hackage.haskell.org/package/language-c99-simple-0.2.3

Please let me know if it works for you.

**Comment by RyanGlScott** [comment]
Thanks, @fdedden! I can confirm that I can build `language-c99-simple-0.2.3` with GHC 9.6.

**Pull request merged**
